### ISSUE TITLE
Ruby_Capstone_Project_Kanban_Setup Review

### ISSUE THREAD

**Issue by Fatima-hub333** [Fatima-hub333/Ruby_Capstone_Project#5]
https://github.com/Fatima-hub333/Ruby_Capstone_Project/projects/1
In this project, I have to work alone. There are no other team members. Here are Screenshots of Marco's conversation on this topic;
![solo_project](https://user-images.githubusercontent.com/89512061/183497251-6e80b6d7-5f4e-4081-ac8e-68983072ae00.png)
![solo](https://user-images.githubusercontent.com/89512061/183497271-2be6c005-1246-48c0-bbe0-8464a61047e3.png)

I will work on 3 divisions of the project. Like, will complete 3 team members' work part. I will cover;
Team Member#1 tasks
Team Member#2 tasks
Team Member#3 tasks

**Comment by DammyShittu** [comment]
Hi @Fatima-hub333,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Regardless of whether the project is a group or solo project I still think it would be better to implement the Group tasks listed in the requirements as it serves as the basis for the other personal tasks.

  For example, if you look closely you can see that Label, Genre, and Author classes are associated with the Item class, which is listed as a group task. In addition to that, the group tasks also contain the creation of the `main.rb` file which serves as the main entry point of the app and so on.

  If all these four tasks seem overwhelming, you can drop team member 3 or team member 2 and 3 tasks, but at minimum, you should implement the group tasks and the team member 1 tasks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fatima-hub333** [comment]
> Hi @Fatima-hub333,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * [ ]  Regardless of whether the project is a group or solo project I still think it would be better to implement the Group tasks listed in the requirements as it serves as the basis for the other personal tasks.
>   For example, if you look closely you can see that Label, Genre, and Author classes are associated with the Item class, which is listed as a group task. In addition to that, the group tasks also contain the creation of the `main.rb` file which serves as the main entry point of the app and so on.
>   If all these four tasks seem overwhelming, you can drop team member 3 or team member 2 and 3 tasks, but at minimum, you should implement the group tasks and the team member 1 tasks.
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you for your valuable feedback. Can you give me 5 minutes on call, please? If possible for you.

**Comment by Fatima-hub333** [comment]
Thank You So much for your valuable feedback. Can you give me 5 minutes on
a zoom call, please? So I can clarify these things with your help.

Kind Regards
Fatima Zahir

**Comment by julie-ify** [comment]
Hi @Fatima-hub333,

## Highlights!
- Good kanban organization ✔️
- Descriptive Tasks

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

# Status: Approved ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
